### ISSUE TITLE
Class labels for indices

### ISSUE THREAD

**Issue by tc64** [IBM/audioset-classification#7]
Hi, I'm having a hard time figuring out which indices in the output correspond to which class labels. Is there a list somewhere? 

For instance, if the output vector has value 1.0 at index 137, which class was selected?

Thanks!

**Comment by stevemar** [comment]
Thanks for asking!

Paging @kmh4321 and @ptitzler to answer!

**Comment by tc64** [comment]
Hey guys, just found the answer I believe, here: http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/class_labels_indices.csv
